networks:
    hmp-network:

services:
    hmp-core:
        container_name: hmp-core
        build:
            context: .
            dockerfile: ./src/Dockerfile
        restart: always
        volumes:
            - ./src:/var/www/html
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - hmp-network
        ports:
            - 9000:80
